# Use base image
FROM bde2020/spark-master:3.1.1-hadoop3.2

# Download PostgreSQL JDBC driver
USER root
RUN mkdir -p /opt/spark/jars/ && wget -O /opt/spark/jars/postgresql-42.2.16.jar https://jdbc.postgresql.org/download/postgresql-42.2.16.jar
